// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjnrfwfyxcbbusysdhmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqbnJmd2Z5eGNiYnVzeXNkaG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDMwNzIsImV4cCI6MjA3MjI3OTA3Mn0.DglvD-Dee0RGTQ2K812-aHMmu2HGVEkNFChnh-SnGSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});